name = "NavAbilitySDK"
uuid = "f3e6a059-199c-4ada-8143-fcefb97e6165"
keywords = ["graphical models", "SLAM", "inference", "factor graphs", "SDK"]
desc = "SDK provided by NavAbility to use their cloud computer infrastructure for sensor fusion."
authors = ["NavAbility <info@navability.io>"]
version = "0.1.0"

[deps]
Diana = "070d9d8b-17a7-5814-83fa-42438ba5c6e0"
DistributedFactorGraphs = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Diana = "0.2"
DistributedFactorGraphs = "0.14"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
