name = "NavAbilitySDK"
uuid = "f3e6a059-199c-4ada-8143-fcefb97e6165"
authors = ["info <info@navability.io>"]
version = "0.1.0"

[deps]
DistributedFactorGraphs = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"

[compat]
DistributedFactorGraphs = "0.12"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
