name: Unit tests

on: 
  push:
    branches:
      - main
      - release**
    tags:
      - v**
  pull_request:
  workflow_dispatch:
    inputs:
      auth_token:
        description: 'NavAbility API auth token'
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: 
          - '1.10'
          - '1.11'
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - id: set_auth_token #TODO get auth token automatically here #49
        name: Set auth token
        run: |
          auth_token=${{ inputs.auth_token }}
          echo "::add-mask::$auth_token"
          echo "nva_auth_token=$auth_token" >> "$GITHUB_OUTPUT"
      - uses: julia-actions/julia-runtest@v1
        env:
          AUTH_TOKEN: ${{ steps.set_auth_token.outputs.nva_auth_token }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using NavAbilitySDK
            DocMeta.setdocmeta!(NavAbilitySDK, :DocTestSetup, :(using NavAbilitySDK); recursive=true)
            doctest(NavAbilitySDK)'
